#!/usr/bin/env bash
# Original from MIT © Sindre Sorhus - sindresorhus.com
# Forked and edited by Ilya Khanataev

# git hook to run a command after `git pull` if a specified file was changed
# Run `chmod +x post-merge` to make it executable then put it into `.git/hooks/`.

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
	echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

# execution

check_run "src/Base/Entity/" "bin/console app:generate-selectors -s './Base/Entity' -t './Base/Selectors'"